import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs/promises';
import { apiCall, login } from './helpers';

async function assertPage(page: Page, width: number) {
  await page.setViewportSize({ width, height: 900 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width + 1);
  expect(await page.evaluate(() => document.body.scrollWidth)).toBeLessThanOrEqual(width + 1);
}

test('administrator uploads, processes, reviews, deactivates, restores and builds an authored source', async ({ page }) => {
  test.setTimeout(120000);
  await login(page, 'admin@example.com');
  const prior = (await apiCall(page, '/corpus/releases')).find((release: { state: string }) => release.state === 'active');
  expect(prior, 'The corpus lifecycle test requires a validated active baseline to restore').toBeTruthy();
  const originalId = prior.id;
  await page.goto('/admin/corpus');
  const title = `Browser source ${Date.now()} — ${'A complete source title remains readable across narrow layouts. '.repeat(3)}`;
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Document title').fill(title);
  await dialog.getByLabel('Edition', { exact: true }).fill('Authored UI verification');
  await dialog.getByLabel('Source URL').fill('https://example.com/authored-browser-fixture');
  await dialog.getByLabel('License / use constraints').fill('Original test fixture; not research evidence');
  await dialog.getByLabel('PDF or text file').setInputFiles({ name: 'authored-browser-source.txt', mimeType: 'text/plain', buffer: Buffer.from('Chapter 1: Photosynthesis\n\n' + 'Photosynthesis uses energy from light to convert carbon dioxide and water into sugars. Chlorophyll absorbs light in chloroplasts. Oxygen is released, while sugars store chemical energy. Plants use those sugars for growth and cellular respiration. '.repeat(12) + `\n\nAuthored test identity ${Date.now()}`) });
  const uploadResponse = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/documents'));
  await dialog.getByRole('button', { name: 'Upload document', exact: true }).click();
  const uploaded = (await (await uploadResponse).json()).data;
  await expect(dialog).toHaveCount(0);
  const record = page.locator('.record').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
  await record.getByRole('button', { name: 'Versions & quality' }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: title, exact: true })).toBeVisible();
  await assertPage(page, 390);
  await page.getByRole('dialog').getByRole('button', { name: /^Close / }).click();
  await record.getByRole('button', { name: 'Process / reprocess' }).click();
  await page.getByRole('button', { name: 'Start processing', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect.poll(async () => (await apiCall(page, `/documents/${uploaded.document.id}`)).latest_state, { timeout: 30000 }).toBe('ready');
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(record.locator('.record-status')).toHaveText('Ready');
  await record.getByRole('button', { name: 'Deactivate source' }).click();
  await expect(record.locator('.record-status')).toHaveText('Deactivated');
  expect((await apiCall(page, `/documents/${uploaded.document.id}`)).active).toBe(false);
  await record.getByRole('button', { name: 'Restore source' }).click();
  await expect(record.locator('.record-status')).toHaveText('Ready');
  expect((await apiCall(page, `/documents/${uploaded.document.id}`)).active).toBe(true);
  await page.getByRole('button', { name: 'Build release', exact: true }).click();
  const releaseName = `Browser release ${Date.now()}`;
  await page.getByLabel('Release name').fill(releaseName);
  await page.getByRole('dialog').getByRole('checkbox', { name: title, exact: false }).check();
  const releaseResponse = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/corpus/releases'));
  await page.getByRole('dialog').getByRole('button', { name: 'Build release', exact: true }).click();
  const receipt = (await (await releaseResponse).json()).data;
  await expect.poll(async () => (await apiCall(page, '/corpus/releases')).find((release: { id: string }) => release.id === receipt.release_id)?.state, { timeout: 30000 }).toBe('validated');
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  const releaseRecord = page.locator('.record').filter({ has: page.getByRole('heading', { name: releaseName, exact: true }) });
  await expect(releaseRecord.getByRole('button', { name: 'Activate release' })).toBeVisible();
  let activated;
  try {
    await releaseRecord.getByRole('button', { name: 'Activate release' }).click();
    await expect(releaseRecord.locator('.record-status')).toHaveText('Active');
    activated = (await apiCall(page, '/corpus/releases')).find((release: { id: string }) => release.id === receipt.release_id);
    expect(activated.state).toBe('active');
    const originalRecord = page.locator('.record').filter({ has: page.getByRole('heading', { name: prior.name, exact: true }) });
    await originalRecord.getByRole('button', { name: 'Rollback to this release' }).click();
    await expect(originalRecord.locator('.record-status')).toHaveText('Active');
  } finally {
    const current = (await apiCall(page, '/corpus/releases')).find((release: { state: string }) => release.state === 'active');
    if (current?.id !== originalId) await apiCall(page, `/corpus/releases/${originalId}/rollback`, 'POST', {});
  }
  const restored = (await apiCall(page, '/corpus/releases')).find((release: { id: string }) => release.id === originalId);
  for (const width of [320, 390, 768, 1024, 1440, 2560]) await assertPage(page, width);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '../artifacts/reports/frontend/admin-corpus-390.png' });
  await fs.writeFile('../artifacts/reports/frontend/admin-corpus.json', JSON.stringify({ source_kind: 'authored browser test fixture', document_id: uploaded.document.id, release_id: receipt.release_id, release_name: releaseName, source_title: title, upload_process_review_deactivate_restore_build: true, actual_activated_release: activated, actual_restored_original: restored }, null, 2));
});

test('administrator runs a frozen public-question evaluation, exports actual outcomes and sees missing inputs', async ({ page }) => {
  test.setTimeout(120000);
  await login(page, 'admin@example.com');
  const configuration = await apiCall(page, '/configurations', 'POST', { kind: 'evaluation', name: `Browser authored evaluation ${Date.now()}`, values: { evaluation_items: [{ question_id: `browser-${Date.now()}`, question_text: 'What is photosynthesis?' }] } });
  const emptyConfiguration = await apiCall(page, '/configurations', 'POST', { kind: 'evaluation', name: `Browser missing inputs ${Date.now()}`, values: {} });
  await page.goto('/admin/experiments');
  await page.getByRole('button', { name: 'Create run', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('combobox', { name: 'Condition', exact: true }).selectOption('E0');
  await dialog.getByRole('combobox', { name: 'Split', exact: true }).selectOption('authored');
  await dialog.getByLabel('Dataset', { exact: true }).fill('authored-ui-workflow');
  await dialog.getByLabel('Dataset revision').fill('browser-fixture-v1');
  await dialog.getByRole('combobox', { name: 'Configuration', exact: true }).selectOption(configuration.id);
  await dialog.getByLabel('Scheduled items').fill('1');
  const createResponse = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/experiments'));
  await dialog.getByRole('button', { name: 'Create draft run' }).click();
  const run = (await (await createResponse).json()).data;
  const record = page.locator(`[data-run-id="${run.id}"]`);
  await record.getByRole('button', { name: 'Freeze', exact: true }).click();
  await expect(record.locator('.record-status')).toHaveText('Frozen');
  await record.getByRole('button', { name: 'Start', exact: true }).click();
  await expect.poll(async () => (await apiCall(page, `/experiments/${run.id}`)).state, { timeout: 30000 }).toBe('completed');
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await record.getByRole('button', { name: 'Results & configuration' }).click();
  await expect(page.getByRole('dialog', { name: 'Experiment results' })).toBeVisible();
  await page.getByRole('dialog').getByText('All scheduled outcomes', { exact: true }).click();
  const results = await apiCall(page, `/experiments/${run.id}/results`);
  await expect(page.getByRole('dialog')).toContainText(run.id);
  await assertPage(page, 320);
  await page.getByRole('dialog').getByRole('button', { name: /^Close / }).click();
  const download = page.waitForEvent('download');
  await record.getByRole('button', { name: 'Export records' }).click();
  const downloaded = await download;
  const exportPath = `../artifacts/reports/frontend/experiment-export-${run.id}.json`;
  await downloaded.saveAs(exportPath);
  const exported = JSON.parse(await fs.readFile(exportPath, 'utf8'));
  expect(exported.run_id).toBe(run.id);
  expect(exported.items).toHaveLength(1);
  const missing = await apiCall(page, '/experiments', 'POST', { protocol_id: 'sciq_openqa', mode: 'benchmark_openqa', condition: 'E0', dataset: 'authored-missing-input', dataset_revision: 'v1', split: 'authored', seed: 42, configuration_id: emptyConfiguration.id, scheduled_count: 1 });
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.locator(`[data-run-id="${missing.id}"]`).getByRole('button', { name: 'Freeze', exact: true })).toBeDisabled();
  await expect(page.locator(`[data-run-id="${missing.id}"]`)).toContainText('Attach the complete question list');
  for (const width of [320, 390, 768, 1440, 2560]) await assertPage(page, width);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: '../artifacts/reports/frontend/admin-experiments-1440.png' });
  await fs.writeFile('../artifacts/reports/frontend/admin-experiments.json', JSON.stringify({ evidence_class: 'mock software workflow, not measured model quality', run_id: run.id, missing_run_id: missing.id, configuration_id: configuration.id, actual_results: results, export_path: exportPath }, null, 2));
});

test('administrator feedback handling saves and reloads the actual review', async ({ page }) => {
  await login(page, 'admin@example.com');
  await page.goto('/admin/feedback');
  const fixture = JSON.parse(await fs.readFile('../evidence/integration/ui_stress_fixture.json', 'utf8'));
  const records = await apiCall(page, '/admin/feedback');
  const stored = records.find((record: { answer_id: string }) => record.answer_id === fixture.answer_id);
  const record = page.locator('.record').filter({ hasText: 'Keep this original feedback when a replacement fails.' });
  await record.getByRole('button', { name: 'Review feedback' }).click();
  await page.getByLabel('Review state').selectOption('reviewed');
  await page.getByLabel('Review note').fill('Verified original feedback remains attached after a failed replacement.');
  await page.getByLabel('Linked issue', { exact: false }).fill('UI-REGEN-001');
  await page.getByRole('button', { name: 'Save review' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await record.getByRole('button', { name: 'Review feedback' }).click();
  await expect(page.getByLabel('Review note')).toHaveValue('Verified original feedback remains attached after a failed replacement.');
  await expect(page.getByLabel('Linked issue', { exact: false })).toHaveValue('UI-REGEN-001');
  await assertPage(page, 320);
  const saved = (await apiCall(page, '/admin/feedback')).find((item: { id: string }) => item.id === stored.id);
  expect(saved.review_state).toBe('reviewed');
  expect(saved.answer_id).toBe(fixture.answer_id);
  await fs.writeFile('../artifacts/reports/frontend/admin-feedback.json', JSON.stringify(saved, null, 2));
});
