import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import { apiCall, assertShell, email, login, password, send } from './helpers';

test('real no-SciQ multi-turn chat, citations, feedback, profile-off and re-login', async ({ page, context }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await login(page);
  const first = await send(page, 'What is photosynthesis?');
  await expect(first.locator('.prose')).toContainText(/photosynthesis|light/i);
  const sessionId = new URL(page.url()).pathname.split('/')[2];
  const firstId = await first.getAttribute('data-answer-id');
  const firstRecord = await apiCall(page, `/answers/${firstId}`);
  expect(firstRecord.response_schema).toBe('chat_response_v1');
  expect(firstRecord.mode).toBe('interactive_chat');
  expect(firstRecord.evidence.length).toBeGreaterThan(0);
  const sourceTrigger = first.getByRole('button', { name: 'Open source 1' }).first();
  await sourceTrigger.focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog', { name: 'Sources' })).toBeVisible();
  await expect(page.locator('.source-passage')).toHaveText(firstRecord.evidence[0].text);
  await expect(page.locator('.source-title')).toHaveText(firstRecord.evidence[0].source_title);
  await page.screenshot({ path: '../artifacts/reports/frontend/evidence-1440.png' });
  await page.keyboard.press('Escape');
  await expect(sourceTrigger).toBeFocused();
  await first.getByRole('button', { name: 'Copy', exact: true }).click();
  expect((await page.evaluate(() => navigator.clipboard.readText())).replaceAll('\r\n', '\n')).toBe(firstRecord.response.answer_text.replaceAll('\r\n', '\n'));
  await first.getByRole('button', { name: 'Feedback', exact: true }).click();
  await page.getByRole('button', { name: 'Helpful', exact: true }).click();
  await page.getByLabel('Comment', { exact: false }).fill('The source passage was useful for checking the explanation.');
  await page.getByRole('button', { name: 'Save feedback', exact: true }).click();
  await expect(page.getByText('Feedback saved for this response.')).toBeVisible();
  await page.getByRole('button', { name: 'Close response feedback' }).click();
  const feedback = await apiCall(page, `/answers/${firstId}/feedback`);
  expect(feedback.helpful).toBe(true); expect(feedback.comment).toContain('source passage');
  const second = await send(page, 'Why does it need light?');
  const secondRecord = await apiCall(page, `/answers/${await second.getAttribute('data-answer-id')}`);
  expect(secondRecord.conversation_snapshot.messages.length).toBeGreaterThanOrEqual(2);
  await page.getByRole('checkbox').uncheck();
  const requestPromise = page.waitForRequest(request => request.method() === 'POST' && request.url().includes('/messages'));
  const third = await send(page, 'Explain it more simply.');
  expect((await requestPromise).postDataJSON()).toEqual({ content: 'Explain it more simply.', use_profile: false });
  const thirdRecord = await apiCall(page, `/answers/${await third.getAttribute('data-answer-id')}`);
  expect(thirdRecord.conversation_snapshot.messages.length).toBeGreaterThanOrEqual(4);
  expect(thirdRecord.profile_snapshot?.use_profile ?? false).toBe(false);
  const latestId = await third.getAttribute('data-answer-id');
  await third.getByRole('button', { name: 'Regenerate', exact: true }).click();
  await expect(page.locator('[data-answer-id]').last()).not.toHaveAttribute('data-answer-id', latestId!, { timeout: 30000 });
  expect(await page.locator('[data-answer-id]').count()).toBe(3);
  const regeneratedId = await page.locator('[data-answer-id]').last().getAttribute('data-answer-id');
  await page.screenshot({ path: '../artifacts/reports/frontend/chat-conversation-1440.png' });
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Password', { exact: true }).fill(password); await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.goto(`/chat/${sessionId}`);
  await expect(page.locator('[data-answer-id]')).toHaveCount(3);
  await expect(page.locator('[data-answer-id]').last()).toHaveAttribute('data-answer-id', regeneratedId!);
  const history = await apiCall(page, `/sessions/${sessionId}/messages?limit=100`);
  expect(history.items).toHaveLength(6);
  await page.locator('[data-answer-id]').first().getByRole('button', { name: 'Feedback', exact: true }).click();
  await expect(page.getByLabel('Comment', { exact: false })).toHaveValue(feedback.comment);
  await fs.writeFile('../artifacts/reports/frontend/no-sciq-journey.json', JSON.stringify({ session_id: sessionId, answer_ids: [firstId, secondRecord.id, regeneratedId], history_count: history.items.length, source_hash: firstRecord.evidence[0].text_hash, applied_profile_version: firstRecord.profile_snapshot?.source_version, feedback_id: feedback.id, actual_ui_api_worker: true, model_mode: 'mock', corpus_kind: 'authored fixture', limits: 'Mock wiring and persistence evidence; no live scientific-quality claim.' }, null, 2));
});

test('responsive widths, breakpoint state preservation, source focus and low-height composer', async ({ page }) => {
  await login(page);
  await send(page, 'What is photosynthesis?');
  const sessionId = new URL(page.url()).pathname.split('/')[2];
  const draft = `My draft stays here across every screen size. ${'A long topic and an unbroken word '.repeat(25)}${'unbroken'.repeat(20)}`;
  const input = page.getByRole('textbox', { name: 'Message Learning Assistant' });
  await input.fill(draft);
  await input.evaluate(node => (node as HTMLTextAreaElement).setSelectionRange(8, 28));
  let posts = 0; page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/messages')) posts++; });
  const rows = [];
  for (const width of [1440, 900, 390, 768, 1440, 320, 375, 640, 1024, 1280, 1920, 2560, 639, 640, 641, 1023, 1024, 1025]) {
    await page.setViewportSize({ width, height: width <= 640 ? 844 : 1000 });
    await expect(input).toHaveValue(draft);
    expect(await input.evaluate(node => [(node as HTMLTextAreaElement).selectionStart, (node as HTMLTextAreaElement).selectionEnd])).toEqual([8, 28]);
    expect(new URL(page.url()).pathname).toBe(`/chat/${sessionId}`);
    rows.push({ requested_width: width, ...await assertShell(page, width) });
    if ([320, 390, 768, 1440, 2560].includes(width)) await page.screenshot({ path: `../artifacts/reports/frontend/chat-${width}.png` });
  }
  expect(posts).toBe(0);
  await page.setViewportSize({ width: 390, height: 844 });
  const source = page.getByRole('button', { name: 'Open source 1' }).first();
  await source.scrollIntoViewIfNeeded(); await source.click();
  await expect(page.getByRole('dialog', { name: 'Sources' })).toBeVisible();
  const modalBounds = await page.getByRole('dialog', { name: 'Sources' }).boundingBox();
  expect(modalBounds!.width).toBe(390);
  await expect(page.getByRole('button', { name: 'Close sources' })).toBeInViewport();
  await page.screenshot({ path: '../artifacts/reports/frontend/evidence-390.png' });
  await page.keyboard.press('Escape'); await expect(source).toBeFocused();
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await page.getByRole('button', { name: 'Close navigation' }).click();
  await expect(page.getByRole('button', { name: 'Toggle sidebar' })).toBeFocused();
  await expect(input).toHaveValue(draft);
  await page.setViewportSize({ width: 844, height: 390 });
  await assertShell(page, 844);
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeInViewport();
  await page.screenshot({ path: '../artifacts/reports/frontend/chat-landscape.png' });
  await fs.writeFile('../artifacts/reports/frontend/chat-responsive-bounds.json', JSON.stringify({ session_id: sessionId, duplicate_posts_on_resize: posts, results: rows, physical_keyboard: 'NOT_AVAILABLE', actual_browser_zoom: 'NOT_RUN_IN_THIS_TEST' }, null, 2));
});

test('social and clarification remain valid conversation turns', async ({ page }) => {
  await login(page);
  const clarification = await send(page, 'Why does it do that?');
  await expect(clarification.getByText('A quick clarification', { exact: true })).toBeVisible();
  const clarified = await send(page, 'I mean photosynthesis.');
  await expect(clarified.locator('.prose')).toContainText(/photosynthesis|light/i);
  const sessionId = new URL(page.url()).pathname.split('/')[2];
  const history = await apiCall(page, `/sessions/${sessionId}/messages?limit=100`);
  expect(history.items[1].answer.response.response_type).toBe('clarification');
  expect(history.items[1].answer.response.citations).toEqual([]);
  await page.locator('.new-chat').click();
  await expect(page.locator('[data-answer-id]')).toHaveCount(0);
  const greeting = await send(page, 'Hello');
  const response = await apiCall(page, `/answers/${await greeting.getAttribute('data-answer-id')}`);
  expect(response.response.response_type).toBe('social');
  expect(response.response.citations).toEqual([]);
});
