"""Bind the original task ledger to final observed evidence without closing research gaps."""

from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
GATE = "evidence/final/software_gate.json"
XML = "evidence/final/pytest.xml"
CORPUS = "evidence/openstax/corpus-report.json"
SOURCE = "docs/execution/source-architecture-audit.md"
CHAT = "evidence/openstax/real-corpus-chat.json"
SCI = "evidence/sciq/acquisition.json"
RESTORE = "evidence/recovery/backup-final-comparisons-20260908/restore-cs30_restore_final_all_20260908.json"


def read(path):
    return json.loads((ROOT / path).read_text("utf-8"))


def sha(path):
    return hashlib.sha256((ROOT / path).read_bytes()).hexdigest()


def main():
    gate = read(GATE)
    if gate["status"] != "passed" or not gate["source_files_unchanged"]:
        raise RuntimeError("A current unchanged-source software gate is required")
    corpus = read(CORPUS)
    chat = read(CHAT)
    if chat["release_id"] != corpus["release_id"] or not chat["status"].startswith("passed"):
        raise RuntimeError("The current real-corpus chat proof must match the publication")
    now = datetime.now(timezone.utc).isoformat()
    path = ROOT / "docs/execution/tasks.json"
    ledger = json.loads(path.read_text("utf-8"))
    rows = ledger["tasks"]
    observed_tests = []
    for case in ET.parse(ROOT / XML).getroot().iter("testcase"):
        observed_tests.append({
            "node": case.attrib["classname"] + "::" + case.attrib["name"],
            "module": case.attrib["classname"].replace(".", "/") + ".py",
            "passed": not any(case.find(tag) is not None for tag in ("failure", "error", "skipped")),
        })
    current_corpus = (
        f"Four actual official full books, 4,638 physical pages, pinned local E5 and PostgreSQL/pgvector. "
        f"Current release {corpus['release_id']} is documented per book in {CORPUS}; "
        "all retained source decisions, actual vector counts, original locators and retrieval outcomes are linked. "
        "Earlier corpus versions and answers remain immutable."
    )
    semantic_limit = "Live answer correctness and independent scientific/relevance/teaching review are not established. Full visual/equation fidelity remains bounded by the source report."
    updates = {}

    def assign(ids, status, observed, remaining="", evidence=(), tests=()):
        for identity in ids.split():
            updates[identity] = (status, observed, remaining, list(evidence), list(tests))

    assign("INT-01 INT-02 CHAT-01", "REAL_FLOW_VERIFIED", "Supplied Word/ZIP/UI sources, source precedence, original numbered scope and actual original Figure 1/page 1 were reconciled into substantive English PRD/SPEC/PLANS and linked detailed specifications.", evidence=[SOURCE, "PRD.md", "SPEC.md", "evidence/source_audit/source_read_manifest.json"])
    assign("INT-03 BE-14 CHAT-11", "REAL_FLOW_VERIFIED", "Current contract/schema/client and chat-scope checks passed; the PostgreSQL upgrade preserved typed old MCQ history, citations and identity. Natural chat retains its two-field input and evaluator-independent context.", evidence=["evidence/contracts/verification.json", "evidence/contracts/chat_scope.json", "evidence/integration/migration-logging-order.log"], tests=["tests/integration/test_legacy_mcq_migration.py"])
    assign("INT-04 BE-01", "MOCK_TEST_PASSED", "Fresh base Compose migration, seeded login and persisted authored chat ran without model keys or SciQ. Final source/runtime checks passed; the real E5 container has separate restored-corpus proof.", "The small base image does not include real model weights; install/use the explicit E5 runtime for the formal corpus.", ["evidence/handovers/candidate-20260908T093208Z/verification.json", "docs/development_checks.md", "evidence/e5-container/runtime-verification.json"])
    assign("INT-05", "REAL_FLOW_VERIFIED", "Current format/lint/boundary typing, contract/schema checks, Python/PostgreSQL tests and frontend type/tests/build passed. Deliberately broken contract/type probes were rejected; the CI workflow and guarded database setup are present.", "Hosted CI execution has not occurred; local equivalent checks are actual evidence.", ["docs/development_checks.md", "evidence/devtools/verification.json"])
    assign("INT-06 INT-07 RET-04 RET-05 GEN-07 BE-08 BE-09 CHAT-05", "REAL_FLOW_VERIFIED", "Actual HTTP, durable worker, real official-source E5 retrieval, budgeted source selection, saved prompt/context/profile traces, request-local citations, feedback and revision history executed on the published corpus.", "Only answering is mock; these are software/provenance observations. " + semantic_limit, [CHAT], ["tests/integration/test_chat_runtime.py", "tests/integration/test_chat_evidence_reuse.py"])
    assign("INT-08 BE-11", "MOCK_TEST_PASSED", "Frozen protocols, immutable public commands, evaluator-private references, all-outcome registration/resume and independent teaching jobs passed actual PostgreSQL integration checks.", "Formal live baseline scores and independent ratings remain pending.", ["docs/execution/audit-evaluation.md"], ["tests/integration/test_evaluation_postgres.py"])
    assign("INT-09", "REAL_FLOW_VERIFIED", "The blocker register distinguishes resolved actual source/model acquisition from user-deferred answering configuration, missing independent labels/ratings and physical-device review.", evidence=["docs/execution/blockers.json"])
    assign("INT-10 CHAT-12", "IMPLEMENTED_UNVERIFIED", "Runnable local product, real corpus, current software evidence, English handover and all original numbered ledgers are delivered with separate research and human-review status. The required deterministic delivery exporter produces eight owner views, seven course-week views and all 60 acceptance references from the canonical ledgers; each grouping contains all 108 tasks exactly once.", "Integrated scientific/human acceptance remains open where the linked original tasks require real provider outputs or independent review.", ["HANDOVER.md", "docs/runbook.md", "docs/execution/acceptance_report.md", "docs/delivery/README.md", "evidence/delivery/2026-09-08T09-52-01Z.json", "evidence/delivery/2026-09-08T09-56-03Z-input-validation.json", CHAT])
    assign("DAT-01 DAT-03 DAT-04 DAT-05 DAT-06 DAT-07 DAT-08 RET-01 RET-02 RET-03 RET-06", "REAL_FLOW_VERIFIED", current_corpus, semantic_limit, [CORPUS, "evidence/openstax/publication.json", "evidence/openstax/formal-source-validation-summary.json", "evidence/openstax/retrieval-verification.json"], ["tests/unit/test_pipeline.py", "tests/unit/test_retrieval.py", "tests/integration/test_corpus_runtime.py"])
    assign("DAT-02 BE-06", "REAL_FLOW_VERIFIED", "All four official original PDFs were actually ingested with immutable source identities. Current tests reject invalid types, path/size abuse and failed sources; repeated originals reuse their hash-defined asset versions.", "Full graphical/equation semantics are not implied by upload or parse success.", [CORPUS, "evidence/openstax/processing-registry.json"], ["tests/integration/test_corpus_runtime.py"])
    assign("DAT-09 QA-02", "REAL_FLOW_VERIFIED", "Official pinned SciQ acquisition records all 13,679 rows and split/file hashes. Actual stem-only export and separate deterministic MCQ preflight ran. All 48 duplicate-option anomalies remain recorded; strict whole-split MCQ rejection is preserved.", "Formal answer-model runs remain separate; a prefix technical rehearsal is not a full dataset result.", [SCI, "docs/sciq_acquisition.md"], ["tests/unit/test_sciq_acquisition.py", "tests/unit/test_evaluation_backend.py"])
    assign("DAT-10 FE-10", "REAL_FLOW_VERIFIED", "Document/reprocessing/source-visibility and immutable release lifecycle are exercised in current PostgreSQL tests. Official-source administrator browser version switching has separate completed evidence in the frontend audit.", "Check each browser attempt and its terminal pointer evidence; earlier interrupted attempts are preserved.", ["docs/execution/audit-ui.md", CORPUS], ["tests/integration/test_corpus_runtime.py"])
    assign("DAT-11", "REAL_FLOW_VERIFIED", "Fixed-window and structure-aware releases were actually built from the same four official sources, v5 parsing/recovery and pinned E5 configuration. Complete source-span coverage, unchanged source-unit text/issues and real-vector relationships were checked; the fixed comparison release remains unactivated.", "Changed chunks require a new reviewed qrel pool. No relevance grades or quality improvements are inferred from coverage/count/vector checks.", ["evidence/chunking/fixed-v5/comparison-summary.json", "evidence/chunking/fixed-v5/formal-source-validation.json", "evidence/chunking/fixed-v5/release-build.json"], ["tests/unit/test_pipeline.py", "tests/unit/test_evaluation_annotations.py"])
    assign("RET-10", "IMPLEMENTED_UNVERIFIED", "An actual one-factor fixed-versus-structure corpus comparison has immutable manifests and verified source coverage. Two actual immutable study designs retain all 1,000 official validation IDs and exact v5 settings: k5 versus3 and pinned E5-small versus E5-base. Official alternate-model metadata is verified; existing single-factor guards accept the designs and reject extra-factor/identity changes. No study calls or alternate embedding release are invented.", "Configuration and paired-schedule preparation is verified; execution count is zero. Compatible judged qrels for v5/fixed are still missing, and the retained v4 null pool cannot be reused as compatible measurement evidence. The alternate model weights/release are unbuilt and user-deferred answering is mock. No unperformed embedding/k study or quality result is claimed.", ["evidence/chunking/fixed-v5/comparison-summary.json", "docs/r0_review_pool.md", "docs/retrieval_diagnostics.md", "docs/controlled_study_designs.md", "evidence/evaluation/ret10-design/preparation.json", "evidence/evaluation/ret10-design/integrity-review.json"], ["tests/unit/test_retrieval.py", "tests/unit/test_evaluation_annotations.py"])
    assign("DAT-12", "REAL_FLOW_VERIFIED", "The English rebuild guide includes actual four-book counts, source/version fields, quality exclusions, recovery and runnable processing commands. Real originals were fully processed again under a new version, and a complete portable restore verified original files and vector identity.", "A fresh model download depends on official hosting; source review is tied to exact PDF hashes and cannot be copied to changed bytes.", ["docs/data_rebuild.md", CORPUS, RESTORE])
    assign("RET-07 RET-08 RET-09 RET-11 QA-09", "REAL_FLOW_VERIFIED", "R0/R1/R2/R3 executed against the same frozen official four-book chunk/vector set with real E5 and pinned cross-encoder inference. Controlled diagnostics retain all scheduled successes/errors, ranked source text, token windows, timings and rank differences.", "Ranking differences and latency observations do not establish relevance improvement without independent qrels. Interrupted and repeated schedules remain distinct; see the terminal reports.", ["docs/retrieval_diagnostics.md", "evidence/retrieval/post-recovery-comparison.json", "evidence/retrieval/post-recovery-summary.json"], ["tests/unit/test_retrieval.py", "tests/integration/test_corpus_runtime.py"])
    assign("GEN-01 GEN-03 GEN-04 GEN-05 GEN-06 GEN-08 GEN-09 GEN-10", "MOCK_TEST_PASSED", "Current strict chat/MCQ schemas, mode-specific prompts, no-gold boundary, simulated provider failures, finite shared retries/repair and deterministic response policies passed their executed tests. Actual-source mock replays retain unsupported/refused cases.", "No real answering-provider semantic or effectiveness result is claimed; the mock adapter has explicit topic/wording limits.", ["docs/execution/mock-evidence-replay.md"], ["tests/unit/test_generation_contracts.py", "tests/unit/test_generation_engine.py", "tests/unit/test_mock_evidence_coverage.py", "tests/integration/test_runtime_faults.py"])
    assign("GEN-02", "WAITING_EXTERNAL", "Configurable live and deterministic mock adapters exist, with strict missing-configuration errors and no silent fallback. The unchanged shared service also switches mock to actual loopback HTTP to mock across three modes; controlled authored outputs and HTTP/schema failures are tested.", "User explicitly deferred actual answering-provider/model/key/budget configuration. The loopback fixture is not a learned model; one configured real answering provider and its actual calls remain unverified.", ["docs/execution/blockers.json", "docs/execution/adapter-replacement-drill.md", "evidence/operations/adapter-replacement/verification.json"], ["tests/unit/test_generation_engine.py", "tests/unit/test_adapter_replacement.py"])
    assign("GEN-11 BE-17", "REAL_FLOW_VERIFIED", "English architecture, schema/migration, installation, accounts, corpus lifecycle, worker, experiment and recovery instructions link executable entry points and actual observations. Historical assets and failed diagnostics remain separately identified.", "Operational instructions distinguish base mock Compose, host real E5 and optional Linux E5; source-package relocation has separate evidence.", ["HANDOVER.md", "docs/runbook.md", "docs/development_checks.md"])
    assign("PER-01 PER-02 PER-04 PER-05 CHAT-07", "MOCK_TEST_PASSED", "Deterministic profile rules/hash, validation/fallback, optimistic versions and per-turn frozen snapshots passed current tests; actual UI/API follows profile-off without clearing session context.", "Model presentation/teaching quality is unverified beyond mock policy and actual input snapshots.", [CHAT, "docs/execution/audit-ui.md"], ["tests/unit/test_profiles.py", "tests/integration/test_chat_runtime.py"])
    assign("PER-03", "IMPLEMENTED_UNVERIFIED", "All three policies were exercised through 12 actual main-service turns: three source-establishing turns and nine short/long/simplification targets. Exact saved profile/policy/source/citation/history checks and one mock call per turn passed. Six target answers and three long-request refusals are retained; short and simplified excerpts were identical to their setup output.", "Requested long explanations did not produce long answers in this mock matrix. Actual differentiated wording, supported meaning and independent scientific review remain unverified; software checks do not close presentation quality.", ["docs/execution/profile-lengths-20260908.md", "evidence/personalisation/profile-lengths-20260908T095207Z/results.json"], ["tests/unit/test_profiles.py", "tests/unit/test_evaluation_study.py"])
    assign("PER-07", "IMPLEMENTED_UNVERIFIED", "All three presentation policies, automatic schema/evidence/profile-version checks and semantic-preservation instructions are implemented and tested. The parser leaves semantic preservation null; actual supported meaning is a separate review question.", "Real model outputs and independent scientific review of facts, negation, formulas and examples are absent.", ["docs/execution/audit-ai.md", "docs/execution/profile-lengths-20260908.md"], ["tests/unit/test_profiles.py", "tests/unit/test_evaluation_study.py"])
    assign("PER-06 PER-08", "MOCK_TEST_PASSED", "Independent C0/C1/C2 execution, frozen source/base-answer linkage, blind-sheet randomization, anchored rubrics and missingness/disagreement handling passed current software tests.", "Actual blinded human scores and real teaching-output quality are not supplied.", ["docs/execution/audit-evaluation.md"], ["tests/unit/test_evaluation_study.py", "tests/unit/test_evaluation_annotations.py", "tests/integration/test_evaluation_postgres.py"])
    assign("PER-09 QA-07 QA-10", "WAITING_EXTERNAL", "Required independent evaluation protocols, annotation/rating tooling and null-safe reports are implemented; input requirements and unavailable results are explicitly recorded.", "Independent relevance/human judgments or user-deferred real answering outputs are missing. No real paired teaching findings or learning gains are claimed.", ["docs/execution/blockers.json", "docs/execution/audit-evaluation.md"], ["tests/unit/test_evaluation_annotations.py", "tests/unit/test_evaluation_study.py"])
    assign("QA-04", "IMPLEMENTED_UNVERIFIED", "An actual late versioned R0 pool contains all 75 question/chunk pairs from 15 saved questions, verified by exact PostgreSQL source spans/hash/release membership. All grades/reviewer fields remain null, with original PDF/book/section/page locators provided for review.", "Independent source judgments remain absent. R1/R2/R3 existed before this pool; the originally requested pre-R1 chronology was not achieved and is not backdated. The v4 pool cannot be reused for v5/fixed chunks without a new compatibility review.", ["docs/r0_review_pool.md", "evidence/retrieval/r0-late-review-pool.json"], ["tests/unit/test_evaluation_annotations.py"])
    assign("BE-02", "REAL_FLOW_VERIFIED", "An actual PostgreSQL database populated at the initial migration upgraded through current migrations with users, sessions, typed MCQ answers and citations preserved. Alembic no longer disables application error logging.", evidence=["evidence/integration/migration-logging-order.log"], tests=["tests/integration/test_legacy_mcq_migration.py", "tests/unit/test_error_log_safety.py"])
    assign("BE-03 BE-04 BE-05 BE-07 BE-10 BE-12 BE-13 BE-15", "REAL_FLOW_VERIFIED", "Current PostgreSQL integration tests exercise owned accounts/sessions/profiles, credential revocation, optimistic conflicts, concurrent feedback/account creation, durable jobs/cancellation, safe error logging and atomic failure publication. Mock/live capabilities remain separate.", "Provider execution is simulated where fault injection is required; actual external exactly-once execution is not promised.", [CHAT, "evidence/recovery/docker-interruption-20260908.json"], ["tests/integration/test_chat_runtime.py", "tests/integration/test_account_feedback_contention.py", "tests/integration/test_runtime_faults.py", "tests/integration/test_operations.py", "tests/unit/test_error_log_safety.py"])
    assign("BE-16", "REAL_FLOW_VERIFIED", "Base Compose startup and a complete backup-v2 portable restore executed. Actual E5 Linux/CUDA queries on the restored database match Windows chunk IDs and passages; original files, supplement hashes and snapshot identities were verified.", "This is local point-in-time recovery, not a disaster-recovery or availability certification; final package checks are separate.", [RESTORE, "evidence/e5-container/runtime-verification.json", "docs/runbook.md"])
    assign("FE-01 FE-02 FE-03 FE-04 FE-05 FE-06 FE-07 FE-08 FE-09 FE-11 CHAT-06", "REAL_FLOW_VERIFIED", "Current frontend types/components/build and real API browser journeys verify chat/account/profile/source/history/revision/feedback and admin consumers. Legacy MCQ answered/refused rows have isolated rendering tests; the learner composer stays natural-language.", "Answering remains mock. Component fixtures and browser/real-source runs have distinct scopes; no physical-device or semantic-quality claim.", ["docs/execution/audit-ui.md", "evidence/ui/legacy-mcq-component-tests.json", CHAT])
    assign("FE-12", "IMPLEMENTED_UNVERIFIED", "Connected English browser journeys, keyboard/focus checks, responsive widths and native desktop zoom are recorded. Actual Enter/Shift+Enter, a persisted suggestion click, polled progress and rejection/draft/history checks now pass; failure alerts are fully visible at 1440/390 without losing intentional older reading positions.", "Physical mobile keyboard, native IME, assistive technology and independent human acceptance remain unverified where required by the responsive subchecks.", ["docs/execution/audit-ui.md", "docs/execution/ui_acceptance.json", "docs/frontend.md", "docs/execution/keyboard-suggestion-verification.md"])
    assign("QA-01 QA-03 QA-05 QA-08 CHAT-09 CHAT-10", "MOCK_TEST_PASSED", "Current tests cover all 12 authored conversation families, gold-free mode adapters, conservative compact-answer metrics, hand-calculated statistical fixtures, frozen runner/resume and retained all-outcome denominators.", "Software fixtures and lexical/statistical proxies do not substitute for live semantic outcomes, source judgments or human ratings.", ["docs/execution/audit-evaluation.md", "evidence/openstax/frontend-prompt-consolidation.json"], ["tests/unit/test_evaluation_metrics.py", "tests/unit/test_evaluation_runner.py", "tests/unit/test_evaluation_backend.py", "tests/integration/test_evaluation_postgres.py"])
    assign("QA-06", "MOCK_TEST_PASSED", "The resumable protocol runner and actual PostgreSQL experiment bridge retain every scheduled outcome, shared-engine requests and private/public export boundaries. The actual four-row SciQ technical rehearsal completed with mock answering. Measured preparation timing now survives export; seven focused regressions and read-only projection of all four actual answers verify the correction while earlier private exports remain unchanged.", "The four-row technical prefix is not a formal benchmark. User-deferred live answering and the full-split MCQ input anomalies remain explicit; no successful calls or private historical outputs were rewritten.", ["docs/execution/evaluator-timing-correction.md", "evidence/evaluation/preparation-timing-correction.json", "evidence/evaluation/restarted-api-timing-projection.json", "evidence/sciq/technical-rehearsal.json"], ["tests/unit/test_evaluation_runner.py", "tests/integration/test_evaluation_postgres.py", "tests/unit/test_evaluation_outcome_timing.py"])
    assign("QA-11 CHAT-08", "MOCK_TEST_PASSED", "Current PostgreSQL/provider fault tests verify persistent retry and regeneration budgets, late-result fencing, cancellation, atomic DB failure, latest-answer revision and original feedback/evidence preservation.", "Provider failures are deliberately simulated. Current actual-corpus browser/API revision checks provide separate end-to-end evidence.", [CHAT], ["tests/integration/test_runtime_faults.py", "tests/integration/test_chat_runtime.py", "tests/integration/test_corpus_runtime.py"])
    assign("QA-12", "REAL_FLOW_VERIFIED", "Actual API/DB/worker/browser journeys and all 12 authored conversation families exercise the connected product; actual-source chat and separate benchmark software protocols use the shared service.", "Mock answer semantic limits, live evaluation and physical-device review remain explicit.", [CHAT, "docs/execution/audit-ui.md", "docs/execution/audit-evaluation.md"], ["tests/integration/test_evaluation_postgres.py", "tests/integration/test_chat_runtime.py"])
    assign("QA-13", "REAL_FLOW_VERIFIED", "Actual local chat and separate evaluation/retrieval workload timings retain environment, corpus, scheduled counts, failures, response types and unknown cost. Preparation/retrieval/generation wall time and adapter-measured latency are distinguished.", "Small-sample local descriptive timings are not an SLA or real-provider latency/cost estimate.", ["docs/performance.md", "evidence/performance/chat-two-sessions.json", "evidence/sciq/technical-rehearsal.json", "evidence/sciq/technical-timing-summary.json", "evidence/evaluation/preparation-timing-correction.json"])
    assign("QA-14", "REAL_FLOW_VERIFIED", "Every original task/check identifier, dependency and source requirement is retained; current observed tests and artifacts are linked per item with remaining scientific/human scope. This audit does not convert unperformed work into acceptance.", "Any linked external or unverified clause remains open even though the audit itself ran.", [SOURCE, "docs/execution/acceptance_report.md", "docs/execution/ui_acceptance.json"])
    assign("CHAT-02 CHAT-03 CHAT-04", "MOCK_TEST_PASSED", "Current deterministic conversation tests verify bounded owned history, immutable snapshots, versioned extractive summaries, local referents, topic correction and reuse eligibility; real official-corpus requests retain the actual prepared queries.", "Broad real-answer semantic correctness is not established by deterministic query fixtures.", [CHAT], ["tests/unit/test_conversation.py", "tests/integration/test_chat_evidence_reuse.py", "tests/integration/test_runtime_faults.py"])

    assert set(updates) == {row["task_id"] for row in rows}, sorted({row["task_id"] for row in rows} - set(updates))
    for row in rows:
        status, observed, remaining, evidence, modules = updates[row["task_id"]]
        evidence = [GATE, XML] + evidence
        versioned_names = {"publication.json", "formal-source-validation-summary.json", "retrieval-verification.json", "processing-registry.json"}
        evidence = [corpus["evidence_directory"] + "/" + Path(p).name if p.startswith("evidence/openstax/") and Path(p).name in versioned_names else p for p in evidence]
        missing = [p for p in evidence if not (ROOT / p).exists()]
        if missing:
            raise RuntimeError(f"Missing real evidence for {row['task_id']}: {missing}")
        row.setdefault("verification_history", []).append({
            "observed_at": row.get("reconciled_at"), "status": row["status"],
            "component_statuses": row.get("component_statuses", []), "remaining_scope": row.get("remaining_scope"),
        })
        relevant = [item for item in observed_tests if item["module"] in modules]
        if modules and (not relevant or not all(item["passed"] for item in relevant)):
            raise RuntimeError("Relevant current tests missing or unsuccessful: " + row["task_id"])
        row.update(
            status=status, implementation_status=status, verification_status=status,
            reconciliation_note=observed, remaining_scope=remaining,
            evidence_paths=list(dict.fromkeys(evidence)), reconciled_at=now,
            completion_claim=False, actual_completed_at=None,
            user_status_definition=ledger["status_definitions"][status],
            evidence=evidence,
            actual_commands=["python -m scripts.verify.all --mode mock"],
            current_test_nodes=[item["node"] for item in relevant],
            current_test_evidence={"path": XML, "sha256": sha(XML), "run_completed_at": gate["executed_at"]},
            component_statuses=[{"component": "observed task scope", "status": status, "detail": observed, "evidence_paths": evidence}, {"component": "remaining acceptance scope", "status": "IMPLEMENTED_UNVERIFIED" if remaining else "REAL_FLOW_VERIFIED", "detail": remaining or "No additional task-specific software gap identified; independent overall acceptance is not inferred."}],
        )
        row["implementation_trace"]["mapping_status"] = "CURRENT_OBSERVATIONS_WITH_EXPLICIT_LIMITS"
        row["implementation_trace"]["limitation"] = remaining
        if modules:
            row["implementation_trace"]["concrete_test_paths"] = modules
    ledger.update(reconciled_at=now, reconciliation_phase="current_real_corpus_and_remaining_local_delivery", project_complete=False, status_note="Original scope and historical observations preserved; current per-row component evidence and remaining acceptance are explicit.")
    ledger["corpus_checkpoint"] = {"observed_at": corpus["observed_at"], "release_id": corpus["release_id"], "official_release_published": True, "full_book_vectors_verified": True, "real_vector_count": sum(book["database_vectors"]["vectors"] for book in corpus["books"]), "dimension": 384, "remaining": semantic_limit}
    path.write_text(json.dumps(ledger, indent=2, ensure_ascii=False) + "\n", "utf-8")
    print("Updated all 108 original task rows from current evidence; research/human requirements remain explicit.")


if __name__ == "__main__":
    main()
