"""Add owner memory, task state, source fragments and controlled presentations."""

from alembic import op
import sqlalchemy as sa

revision = "c8d42e5a901f"
down_revision = "b6f924d031ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_memory_settings",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("revocation_epoch", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_table(
        "learning_memory_snapshots",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("revocation_epoch", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("invalidated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_memory_snapshots_owner_id"),
        "learning_memory_snapshots",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "learning_memory_suppressions",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=False),
        sa.Column("canonical_key", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "source_message_id", "canonical_key"),
    )
    op.create_index(
        op.f("ix_learning_memory_suppressions_owner_id"),
        "learning_memory_suppressions",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "learning_memory_entries",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("canonical_key", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "category", "canonical_key"),
    )
    op.create_index(
        op.f("ix_learning_memory_entries_owner_id"),
        "learning_memory_entries",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "learning_tasks",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("initial_message_id", sa.String(length=36), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("task_type", sa.String(length=40), nullable=False),
        sa.Column("teaching_mode", sa.String(length=20), nullable=False),
        sa.Column("help_level", sa.Integer(), nullable=False),
        sa.Column("exposure_epoch", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["initial_message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_tasks_owner_id"), "learning_tasks", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_tasks_session_id"), "learning_tasks", ["session_id"], unique=False
    )
    op.create_table(
        "learning_memory_revisions",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("entry_version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["learning_memory_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "entry_version"),
    )
    op.create_index(
        op.f("ix_learning_memory_revisions_entry_id"),
        "learning_memory_revisions",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "private_answer_drafts",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("memory_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("phase", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_snapshot_id"],
            ["learning_memory_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["answer_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_private_answer_drafts_request_id"),
        "private_answer_drafts",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "source_fragments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("processing_id", sa.String(length=36), nullable=False),
        sa.Column("source_unit_id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("start", sa.Integer(), nullable=False),
        sa.Column("end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("block_kind", sa.String(length=40), nullable=False),
        sa.Column("mapping_quality", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processing_id"],
            ["processing_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_unit_id"],
            ["source_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_fragments_processing_id"),
        "source_fragments",
        ["processing_id"],
        unique=False,
    )
    op.create_table(
        "answer_attributions",
        sa.Column("answer_id", sa.String(length=36), nullable=False),
        sa.Column("strategy", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("answer_id"),
    )
    op.create_table(
        "answer_presentations",
        sa.Column("answer_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["learning_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("answer_id"),
    )
    op.create_table(
        "learning_exposures",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("answer_id", sa.String(length=36), nullable=True),
        sa.Column("presentation_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["answer_presentations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["learning_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_learning_exposures_owner_id"), "learning_exposures", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_exposures_owner_id"), table_name="learning_exposures")
    op.drop_table("learning_exposures")
    op.drop_table("answer_presentations")
    op.drop_table("answer_attributions")
    op.drop_index(op.f("ix_source_fragments_processing_id"), table_name="source_fragments")
    op.drop_table("source_fragments")
    op.drop_index(op.f("ix_private_answer_drafts_request_id"), table_name="private_answer_drafts")
    op.drop_table("private_answer_drafts")
    op.drop_index(
        op.f("ix_learning_memory_revisions_entry_id"), table_name="learning_memory_revisions"
    )
    op.drop_table("learning_memory_revisions")
    op.drop_index(op.f("ix_learning_tasks_session_id"), table_name="learning_tasks")
    op.drop_index(op.f("ix_learning_tasks_owner_id"), table_name="learning_tasks")
    op.drop_table("learning_tasks")
    op.drop_index(op.f("ix_learning_memory_entries_owner_id"), table_name="learning_memory_entries")
    op.drop_table("learning_memory_entries")
    op.drop_index(
        op.f("ix_learning_memory_suppressions_owner_id"), table_name="learning_memory_suppressions"
    )
    op.drop_table("learning_memory_suppressions")
    op.drop_index(
        op.f("ix_learning_memory_snapshots_owner_id"), table_name="learning_memory_snapshots"
    )
    op.drop_table("learning_memory_snapshots")
    op.drop_table("learning_memory_settings")
    # ### end Alembic commands ###
