import { useEffect, useState, type FormEvent } from 'react';
import { Check, GraduationCap } from 'lucide-react';
import { api, patch, post, put } from './api';
import { Button, ErrorNotice, Loading, titleCase } from './components';
import type { Profile, User } from './types';

export function ProfilePage({ profile, onSaved }: { profile: Profile | null; onSaved: (profile: Profile) => void }) {
  const [form, setForm] = useState(profile); const [topics, setTopics] = useState(profile?.topics?.join('\n') || ''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState<unknown>(null);
  useEffect(() => { setForm(profile); setTopics(profile?.topics?.join('\n') || ''); }, [profile]);
  if (!form) return <div className="content-page"><Loading>Loading your preferences…</Loading></div>;
  const change = (value: Partial<Profile>) => { setForm({ ...form, ...value }); setSaved(false); };
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const updated = await put<Profile>('/profiles/me', { ...form, topics: topics.split('\n').map(x => x.trim()).filter(Boolean) }); onSaved(updated); setSaved(true); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  const reset = async () => { setBusy(true); setError(null); try { onSaved(await post<Profile>('/profiles/me/reset', { version: form.version })); setSaved(true); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  return <div className="content-page settings-page"><span className="eyebrow"><GraduationCap size={18} />Your learning experience</span><h1>Make explanations work for you.</h1><p className="page-intro">These are your preferences, not a measure of your ability. You can always ask for a simpler explanation or more detail in a conversation.</p><form className="stack" onSubmit={save}><fieldset><legend>Explanation level</legend><div className="level-options">{(['beginner', 'intermediate', 'advanced'] as const).map(level => <label className={`level-option ${form.level === level ? 'active' : ''}`} key={level}><input type="radio" name="level" value={level} checked={form.level === level} onChange={() => change({ level })} /><span><strong>{titleCase(level)}</strong><small>{level === 'beginner' ? 'Build from the basics, with clear steps.' : level === 'intermediate' ? 'Connect concepts with useful context.' : 'Explore precise detail and assumptions.'}</small></span></label>)}</div></fieldset><div className="form-grid"><label>Explanation style<select value={form.style} onChange={e => change({ style: e.target.value as Profile['style'] })}><option value="concise">Concise</option><option value="detailed">Detailed</option><option value="socratic">Guided questions</option></select></label><label>Response language<select value={form.language} onChange={() => {}}><option value="en">English</option></select><small>English is the current supported corpus language.</small></label></div><label>Topics you are interested in <span className="secondary">(optional)</span><textarea rows={4} value={topics} onChange={e => { setTopics(e.target.value); setSaved(false); }} placeholder="One topic per line" /><small>Up to 20 topics, 200 characters each. These are self-reported interests.</small></label><ErrorNotice error={error} action={<Button onClick={async () => { onSaved(await api.profile()); setError(null); }}>Reload saved preferences</Button>} /><div className="form-actions"><Button type="submit" className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save preferences'}</Button><Button onClick={reset} disabled={busy}>Reset to defaults</Button>{saved && <span className="saved" role="status"><Check size={16} />Preferences saved</span>}</div><p className="secondary">Current revision {form.version}. Changes apply to future turns. Earlier responses keep the preferences used when they were created.</p></form></div>;
}

export function AccountPage({ user, onSaved, onPasswordChanged }: { user: User; onSaved: (user: User) => void; onPasswordChanged: () => void }) {
  const [name, setName] = useState(user.full_name); const [oldPassword, setOldPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null); const [saved, setSaved] = useState(false);
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { onSaved(await patch<User>('/users/me', { full_name: name })); setSaved(true); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  const password = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { await post('/users/me/password', { old_password: oldPassword, new_password: newPassword }); onPasswordChanged(); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  return <div className="content-page settings-page"><span className="eyebrow">Account settings</span><h1>Your account</h1><p className="page-intro">{user.email}</p><ErrorNotice error={error} /><form className="stack settings-section" onSubmit={save}><label>Display name<input required maxLength={120} value={name} onChange={e => { setName(e.target.value); setSaved(false); }} autoComplete="name" /></label><div className="form-actions"><Button type="submit" className="primary" disabled={busy}>Save name</Button>{saved && <span role="status">Name saved</span>}</div></form><form className="stack settings-section" onSubmit={password}><h2>Change password</h2><label>Current password<input type="password" autoComplete="current-password" required value={oldPassword} onChange={e => setOldPassword(e.target.value)} /></label><label>New password<input type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={newPassword} onChange={e => setNewPassword(e.target.value)} /><small>Use at least ten characters. You will sign in again after the change.</small></label><Button type="submit" className="primary" disabled={busy}>{busy ? 'Saving…' : 'Change password'}</Button></form></div>;
}
